version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: lb4
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  lb4_app:
    build: .
    container_name: lb4_app
    restart: always
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=mysql_db
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=userpassword
      - DB_DATABASE=lb4
    depends_on:
      - mysql_db

volumes:
  mysql_data:
